travis:
  secure:
    BINSTAR_TOKEN: Jby+Go6SfDMz6NaK2INsuWY87E8JFxUf6flQkK80aWQlJWp7wdW0DHUTE5S7xCyA2fJzXScFnYv7Q7Inv5RKc2idJt4DEyWEnOEQZfZfWxYqIIPGzUJ+0YP3SY/SChtW+m3UMyDAxaAL4PMcLvLY3GWBgD02lb7osSnLSpx7K4qwUlODrYQ2k0ViBR5SSN4/KT5L5TBGW7gHbOg2+etps8kHeLcV3CsOBPcRghvb6k9lQ/Wt5nmWqu4Ijh/xYcOZGaiE/zyS8zc5Vp/zQc/pp+vWtDtXFYmc+wlfy2qtvZPLhyqeATmuHbegTUDlgL1PbqXFtZwfk6esG6YcCVYCgszxmpt3KJXMs8Z0Qldo6uUv8+bARrHg1dW/bg99OdBdzKoH/W3kwBTAe0RQWOR42Ij/di8YHhZfABm3reHxef3PiW5Th9hMFKNPTdhnHmviwJ0OCsTDgZoo0yxwGh9KEfusdIeBLVO7Pjj9gGsj1mtAZ8IfujUR10OsX+jLtBJwuRYY1CQ/C4PrDP4/sEJghkmOrnU6lRpRTAqUo9vw7bQgiRCQwllLbFRt6HsYfP9hDxUJqfs/zTIn+XhUzr2l5Qj9TGcyRZ+Sn4FO3xLLm/uaSYdLZpN5Bj6mNNOBLyky7zc2jm9PcsuJxfXClk3GNHS2t3bgXiX9k2OWQ4ouuGI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
